/** Kid-written meanings for every curated word. Beats any dictionary API:
 *  those explain BODY as "an entity" and NOSE as "a protuberance". */
export const WORD_MEANINGS: Record<string, string> = {
  ANT: 'A tiny insect that walks in a line.',
  APPLE: 'A crunchy round fruit, red or green.',
  ARM: 'The part of you from shoulder to hand.',
  AUNT: 'Your mum or dad’s sister.',
  BABY: 'A very young child.',
  BACK: 'The part of you behind your tummy.',
  BAG: 'You carry your things in it.',
  BALL: 'A round toy you bounce and kick.',
  BANANA: 'A long yellow fruit you peel.',
  BEAN: 'A little seed you can eat.',
  BEAR: 'A big furry animal with strong paws.',
  BED: 'Where you sleep at night.',
  BEE: 'A buzzy insect that makes honey.',
  BELL: 'It rings to tell you something.',
  BERRY: 'A tiny sweet fruit.',
  BIKE: 'Two wheels you pedal.',
  BIRD: 'An animal with feathers that can fly.',
  BLACK: 'The colour of the night sky.',
  BLOOM: 'When a flower opens up.',
  BLUE: 'The colour of the sky and the sea.',
  BOAT: 'It floats and carries you on water.',
  BONE: 'The hard parts inside your body.',
  BOOK: 'Pages with stories to read.',
  BRAVE: 'Doing something even when it feels scary.',
  BREAD: 'Soft food baked from flour.',
  BREEZE: 'A soft, gentle wind.',
  BROTHER: 'A boy with the same parents as you.',
  BROWN: 'The colour of chocolate and tree trunks.',
  BUS: 'A big vehicle that carries lots of people.',
  CAKE: 'A sweet treat for birthdays.',
  CALM: 'Quiet and peaceful, not upset.',
  CAR: 'Four wheels that drive you places.',
  CARE: 'Looking after someone kindly.',
  CART: 'A little wagon for carrying things.',
  CAT: 'A furry pet that says meow.',
  CATCH: 'To grab something flying towards you.',
  CHAIR: 'You sit on it.',
  CHALK: 'A soft stick for writing on a board.',
  CHILD: 'A young person, like you.',
  CHIN: 'The part of your face below your mouth.',
  CHIP: 'A thin crispy slice of potato.',
  CLAP: 'Hitting your hands together.',
  CLASS: 'A group of kids learning together.',
  CLOCK: 'It shows you what time it is.',
  CLOUD: 'Fluffy white water floating in the sky.',
  CLOUDY: 'When the sky is full of clouds.',
  COLD: 'Not warm at all, like ice.',
  COOL: 'A little bit cold, in a nice way.',
  CORN: 'Yellow seeds that grow on a cob.',
  COW: 'A farm animal that gives us milk.',
  CRAB: 'A sea animal with claws that walks sideways.',
  CUP: 'You drink from it.',
  CYAN: 'A bright blue-green colour.',
  DAD: 'Your father.',
  DANCE: 'Moving your body to music.',
  DEER: 'A gentle forest animal that runs fast.',
  DESK: 'A table for school work.',
  DIRT: 'Loose brown earth on the ground.',
  DOG: 'A friendly pet that barks.',
  DOOR: 'You open it to go in or out.',
  DRAW: 'Making a picture with a pen or crayon.',
  DRY: 'Not wet at all.',
  DUCK: 'A bird that swims and says quack.',
  EAR: 'You hear with it.',
  EGG: 'Birds lay them, and we cook them.',
  EYE: 'You see with it.',
  FACE: 'The front of your head.',
  FAMILY: 'The people who love and live with you.',
  FISH: 'An animal that swims and breathes underwater.',
  FLOOR: 'The part of a room you walk on.',
  FLOWER: 'The pretty coloured part of a plant.',
  FOG: 'A cloud that sits on the ground.',
  FOOT: 'You stand and walk on it.',
  FOX: 'A clever wild animal with a bushy tail.',
  FRIEND: 'Someone you like to play with.',
  FROG: 'A green hopper that lives near water.',
  FUN: 'Something that makes you happy to do.',
  FUNNY: 'Something that makes you laugh.',
  GALAXY: 'A huge group of stars in space.',
  GAME: 'Something you play, with rules.',
  GARDEN: 'A place where plants grow.',
  GATE: 'A door in a fence or wall.',
  GLAD: 'Feeling happy about something.',
  GLUE: 'Sticky stuff that joins things together.',
  GOAT: 'A farm animal that climbs and nibbles.',
  GOLD: 'A shiny yellow treasure colour.',
  GRASS: 'The green plants covering a lawn.',
  GRAY: 'The colour of rain clouds.',
  GREEN: 'The colour of leaves and grass.',
  HAIL: 'Little balls of ice falling from the sky.',
  HAIR: 'It grows on top of your head.',
  HAM: 'Pink meat you put in a sandwich.',
  HAND: 'You hold and wave with it.',
  HAPPY: 'Feeling really good inside.',
  HEAD: 'The top of you, where your face is.',
  HEART: 'It beats inside you and pumps your blood.',
  HEN: 'A farm bird that lays eggs.',
  HIDE: 'To go where nobody can see you.',
  HILL: 'A small mountain you can walk up.',
  HOME: 'The place where you live.',
  HOPE: 'Wishing for something good to happen.',
  HORSE: 'A big animal you can ride.',
  HOT: 'Very warm, like the sun.',
  HUG: 'Wrapping your arms around someone.',
  HUNGRY: 'When your tummy wants food.',
  ICY: 'Covered in ice and very slippery.',
  INK: 'The coloured liquid inside a pen.',
  JADE: 'A pretty green stone colour.',
  JAM: 'Sweet fruit spread for your bread.',
  JET: 'A very fast plane.',
  JOY: 'A big happy feeling.',
  JUICE: 'A drink squeezed from fruit.',
  JUMP: 'Pushing off the ground with both feet.',
  KEY: 'A little metal thing that opens locks.',
  KICK: 'Hitting something with your foot.',
  KID: 'Another word for a child.',
  KIND: 'Being nice and helping others.',
  KISS: 'A little touch with your lips.',
  KNEE: 'The bendy middle of your leg.',
  LAKE: 'A big pool of water with land around it.',
  LAMB: 'A baby sheep.',
  LAMP: 'It makes light in a room.',
  LAUGH: 'The happy sound you make at something funny.',
  LEAF: 'The flat green part of a plant.',
  LEARN: 'Finding out how to do something new.',
  LEG: 'You walk and run with them.',
  LIME: 'A bright green colour, like the fruit.',
  LION: 'A big cat with a loud roar.',
  LIP: 'The soft edge of your mouth.',
  LOVE: 'Caring about someone very much.',
  LOVED: 'When people care about you a lot.',
  MAD: 'Feeling cross or angry.',
  MAP: 'A picture showing where places are.',
  MATH: 'Working things out with numbers.',
  MILK: 'A white drink that comes from cows.',
  MOM: 'Your mother.',
  MOON: 'The bright round rock in the night sky.',
  MOTHER: 'Your mum.',
  MUD: 'Wet, squishy dirt.',
  NANA: 'A name some kids use for grandma.',
  NAVY: 'A very dark blue.',
  NECK: 'It joins your head to your body.',
  NEST: 'The little home a bird builds.',
  NICE: 'Kind and pleasant.',
  NOSE: 'You smell and breathe with it.',
  NOTE: 'A short message you write down.',
  NUT: 'A hard little food with a shell.',
  OLIVE: 'A dark yellow-green colour.',
  OVEN: 'The hot box where food is baked.',
  OWL: 'A night bird that says hoot.',
  PAGE: 'One sheet in a book.',
  PAPA: 'A name some kids use for dad.',
  PAPER: 'Thin white sheets you write on.',
  PARK: 'A green place to play outside.',
  PASTA: 'Food like spaghetti and macaroni.',
  PEAR: 'A sweet fruit shaped like a bell.',
  PEN: 'You write with it, using ink.',
  PENCIL: 'You write with it and can rub it out.',
  PIE: 'Fruit baked inside pastry.',
  PIG: 'A pink farm animal that says oink.',
  PINK: 'A light red colour.',
  PLANE: 'It flies people through the sky.',
  PLANET: 'A big round world going around a star.',
  PLUM: 'A juicy purple fruit.',
  POND: 'A small pool of water.',
  PROUD: 'Feeling great about something you did.',
  PURPLE: 'The colour you get from red and blue.',
  PUZZLE: 'Pieces you fit together.',
  RABBIT: 'A hopping animal with long ears.',
  RACE: 'Running to see who is fastest.',
  RAIL: 'The metal track a train runs on.',
  RAIN: 'Water falling from the clouds.',
  READ: 'Looking at words and understanding them.',
  RED: 'The colour of strawberries.',
  RICE: 'Small white grains you cook and eat.',
  RIDE: 'Sitting on something that carries you along.',
  ROAD: 'The path that cars drive on.',
  ROCK: 'A hard piece of stone.',
  ROCKET: 'It blasts off into space.',
  ROLL: 'A small round loaf of bread.',
  ROOF: 'The top of a house that keeps rain out.',
  ROOM: 'A space inside a house.',
  ROSE: 'A pretty flower with a lovely smell.',
  RUG: 'A soft mat on the floor.',
  RULER: 'A straight stick for measuring.',
  RUN: 'Moving with your legs, faster than walking.',
  SAD: 'Feeling unhappy.',
  SAFE: 'Away from anything that could hurt you.',
  SAND: 'Tiny bits of rock on the beach.',
  SCHOOL: 'Where you go to learn.',
  SEED: 'A tiny thing a plant grows from.',
  SHELF: 'A flat board for keeping things on.',
  SHIP: 'A very big boat.',
  SHY: 'Feeling quiet around new people.',
  SILLY: 'Being funny in a goofy way.',
  SING: 'Making music with your voice.',
  SINK: 'A basin with a tap, for washing.',
  SISTER: 'A girl with the same parents as you.',
  SKIN: 'It covers your whole body.',
  SKIP: 'Hopping along, step and jump.',
  SKY: 'The big space above you.',
  SLIDE: 'You zoom down it at the playground.',
  SMILE: 'When your mouth turns up, happily.',
  SNOW: 'Soft white flakes that fall when it is cold.',
  SOAP: 'It helps wash your hands clean.',
  SOFA: 'A long soft seat for a few people.',
  SOUP: 'A warm dinner you eat with a spoon.',
  SPELL: 'Saying the letters of a word in order.',
  STAR: 'A tiny bright light in the night sky.',
  STONE: 'A small hard rock.',
  STOP: 'To not go any further.',
  STORM: 'Wild weather with wind and rain.',
  SUN: 'The bright star that warms our day.',
  SUNNY: 'When the sun is shining.',
  SWING: 'A seat on ropes that swings you.',
  TABLE: 'You eat and work at it.',
  TAN: 'A light sandy brown.',
  TAXI: 'A car you pay to ride in.',
  TEA: 'A warm drink made with leaves.',
  TEACHER: 'The person who helps you learn.',
  TEAL: 'A blue-green colour.',
  TEST: 'Questions that show what you know.',
  THROW: 'Sending something through the air.',
  THUNDER: 'The loud rumble after lightning.',
  TIGER: 'A big orange cat with black stripes.',
  TIRED: 'When your body wants to rest.',
  TOE: 'One of the five on your foot.',
  TOOTH: 'One of the white bits you chew with.',
  TOWEL: 'Cloth for drying yourself.',
  TOY: 'Something you play with.',
  TRAIN: 'Carriages that run along a track.',
  TREE: 'A tall plant with a trunk and leaves.',
  TRUCK: 'A big vehicle that carries heavy loads.',
  TWIG: 'A thin little branch.',
  UNCLE: 'Your mum or dad’s brother.',
  VAN: 'A boxy vehicle for carrying things.',
  WALL: 'The side of a room or building.',
  WARM: 'A little bit hot, and cosy.',
  WAVE: 'Water rolling onto the beach.',
  WET: 'Covered in water.',
  WHEEL: 'A round part that rolls.',
  WHITE: 'The colour of snow and milk.',
  WIND: 'Air moving fast outside.',
  WINDOW: 'Glass you look through in a wall.',
  WOLF: 'A wild animal like a big dog.',
  WRITE: 'Making words with a pen or pencil.',
  YELLOW: 'The colour of the sun and bananas.',
}

export function meaningOf(word: string): string | undefined {
  return WORD_MEANINGS[word.toUpperCase()]
}
