import { filterKidWords, preferFresh, type WordEntry } from './wordApi'
import { meaningOf } from './wordMeanings'

export type WordLevelId =
  | 'animals'
  | 'colors'
  | 'school'
  | 'home'
  | 'play'
  | 'food'
  | 'nature'
  | 'family'
  | 'body'
  | 'weather'
  | 'transport'
  | 'feelings'

export type WordLevel = {
  id: WordLevelId
  title: string
  emoji: string
  /** Kid-curated word pool for this theme */
  words: string[]
}

export const WORD_LEVEL_ORDER: WordLevelId[] = [
  'animals',
  'colors',
  'school',
  'home',
  'play',
  'food',
  'nature',
  'family',
  'body',
  'weather',
  'transport',
  'feelings',
]

export const WORDS_PER_ROUND = 10

export const WORD_LEVELS: Record<WordLevelId, WordLevel> = {
  animals: {
    id: 'animals',
    title: 'Animals',
    emoji: '🐾',
    words: [
      'CAT',
      'DOG',
      'BIRD',
      'FISH',
      'FROG',
      'BEAR',
      'DUCK',
      'LION',
      'PIG',
      'COW',
      'HEN',
      'ANT',
      'FOX',
      'OWL',
      'BEE',
      'GOAT',
      'LAMB',
      'WOLF',
      'DEER',
      'CRAB',
    ],
  },
  colors: {
    id: 'colors',
    title: 'Colors',
    emoji: '🎨',
    words: [
      'RED',
      'BLUE',
      'PINK',
      'GOLD',
      'GREEN',
      'BLACK',
      'WHITE',
      'BROWN',
      'GRAY',
      'TEAL',
      'TAN',
      'NAVY',
      'LIME',
      'ROSE',
      'JADE',
      'PLUM',
      'CYAN',
      'OLIVE',
    ],
  },
  school: {
    id: 'school',
    title: 'School',
    emoji: '📚',
    words: [
      'BOOK',
      'PEN',
      'DESK',
      'BAG',
      'READ',
      'MATH',
      'GLUE',
      'MAP',
      'BELL',
      'NOTE',
      'CLASS',
      'INK',
      'PAPER',
      'RULER',
      'CHALK',
      'PAGE',
      'TEST',
      'WRITE',
      'SPELL',
      'LEARN',
    ],
  },
  home: {
    id: 'home',
    title: 'Home',
    emoji: '🏠',
    words: [
      'BED',
      'DOOR',
      'CUP',
      'LAMP',
      'SOFA',
      'ROOM',
      'WALL',
      'SINK',
      'OVEN',
      'RUG',
      'CHAIR',
      'GATE',
      'ROOF',
      'FLOOR',
      'SHELF',
      'TOWEL',
      'SOAP',
      'CLOCK',
      'KEY',
      'TABLE',
    ],
  },
  play: {
    id: 'play',
    title: 'Play',
    emoji: '🎮',
    words: [
      'BALL',
      'GAME',
      'JUMP',
      'SING',
      'DRAW',
      'TOY',
      'SLIDE',
      'SWING',
      'RACE',
      'DANCE',
      'HIDE',
      'RUN',
      'SKIP',
      'KICK',
      'THROW',
      'CATCH',
      'CLAP',
      'LAUGH',
      'SMILE',
      'FUN',
    ],
  },
  food: {
    id: 'food',
    title: 'Food',
    emoji: '🍎',
    words: [
      'APPLE',
      'MILK',
      'BREAD',
      'RICE',
      'CAKE',
      'SOUP',
      'EGG',
      'CORN',
      'PEAR',
      'JUICE',
      'PASTA',
      'BEAN',
      'NUT',
      'HAM',
      'PIE',
      'JAM',
      'TEA',
      'ROLL',
      'CHIP',
      'BERRY',
    ],
  },
  nature: {
    id: 'nature',
    title: 'Nature',
    emoji: '🌳',
    words: [
      'TREE',
      'LEAF',
      'SUN',
      'MOON',
      'STAR',
      'ROCK',
      'LAKE',
      'HILL',
      'SEED',
      'CLOUD',
      'GRASS',
      'SAND',
      'WAVE',
      'POND',
      'DIRT',
      'MUD',
      'NEST',
      'TWIG',
      'BLOOM',
      'STONE',
    ],
  },
  family: {
    id: 'family',
    title: 'Family',
    emoji: '👨‍👩‍👧',
    words: [
      'MOM',
      'DAD',
      'BABY',
      'AUNT',
      'UNCLE',
      'SISTER',
      'LOVE',
      'HUG',
      'KISS',
      'HOME',
      'BROTHER',
      'NANA',
      'PAPA',
      'CHILD',
      'KID',
      'FAMILY',
      'CARE',
      'KIND',
    ],
  },
  body: {
    id: 'body',
    title: 'Body',
    emoji: '💪',
    words: [
      'HAND',
      'FOOT',
      'EYE',
      'EAR',
      'NOSE',
      'ARM',
      'LEG',
      'HAIR',
      'FACE',
      'TOOTH',
      'NECK',
      'KNEE',
      'TOE',
      'LIP',
      'CHIN',
      'BACK',
      'HEAD',
      'SKIN',
      'BONE',
      'HEART',
    ],
  },
  weather: {
    id: 'weather',
    title: 'Weather',
    emoji: '⛅',
    words: [
      'RAIN',
      'SNOW',
      'WIND',
      'HOT',
      'COLD',
      'WARM',
      'STORM',
      'FOG',
      'HAIL',
      'SKY',
      'SUNNY',
      'CLOUDY',
      'ICY',
      'WET',
      'DRY',
      'COOL',
      'BREEZE',
      'THUNDER',
    ],
  },
  transport: {
    id: 'transport',
    title: 'Transport',
    emoji: '🚗',
    words: [
      'CAR',
      'BUS',
      'BIKE',
      'TRAIN',
      'BOAT',
      'SHIP',
      'PLANE',
      'TRUCK',
      'VAN',
      'TAXI',
      'JET',
      'CART',
      'RAIL',
      'ROAD',
      'WHEEL',
      'RIDE',
      'PARK',
      'STOP',
    ],
  },
  feelings: {
    id: 'feelings',
    title: 'Feelings',
    emoji: '😊',
    words: [
      'HAPPY',
      'SAD',
      'MAD',
      'GLAD',
      'BRAVE',
      'CALM',
      'PROUD',
      'SHY',
      'KIND',
      'NICE',
      'FUNNY',
      'SILLY',
      'TIRED',
      'HUNGRY',
      'LOVED',
      'SAFE',
      'HOPE',
      'JOY',
    ],
  },
}

export function getWordLevel(id: WordLevelId): WordLevel {
  return WORD_LEVELS[id]
}

/**
 * Words for one round. The curated lists are the source: Datamuse's "means
 * like" search returned grown-up abstractions for these themes — asking it for
 * BODY words gave "entity", "moral", "system". Each word ships its own kid
 * meaning, so nothing on screen depends on the network.
 */
export function loadLevelWords(id: WordLevelId): WordEntry[] {
  const pool = filterKidWords(WORD_LEVELS[id].words, { min: 3, max: 7 })
  return preferFresh(pool, WORDS_PER_ROUND).map((word) => ({
    word,
    hint: meaningOf(word),
  }))
}
